/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonTable: typeof import('./src/components/CommonTable.vue')['default']
    Confirm: typeof import('./src/components/Confirm.vue')['default']
    QuickMark: typeof import('./src/components/QuickMark.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
